name: Build Jekyll with nbviewer Links

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true
          cache-version: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          # Ensure remote theme is properly cached
          bundle exec jekyll clean

      - name: Convert notebook links and fix asset paths
        run: |
          # Create a Python script to convert links and fix paths
          cat > convert_links.py << 'EOF'
          import os
          import re
          import glob

          def convert_notebook_links(content, repo_name="AET-CS/aet-cs.github.io", branch="main"):
              # Pattern 1: Full GitHub Pages URLs
              pattern1 = r'https://aet-cs\.github\.io(/[^"\s)]*\.ipynb)'
              replacement1 = rf'https://nbviewer.jupyter.org/github/{repo_name}/blob/{branch}\1'
              content = re.sub(pattern1, replacement1, content)

              # Pattern 2: Relative links starting with /
              pattern2 = r'href="(/[^"\s]*\.ipynb)"'
              replacement2 = rf'href="https://nbviewer.jupyter.org/github/{repo_name}/blob/{branch}\1"'
              content = re.sub(pattern2, replacement2, content)

              # Pattern 3: Relative links without leading /
              pattern3 = r'href="(?!http|/)([^"\s]*\.ipynb)"'
              replacement3 = rf'href="https://nbviewer.jupyter.org/github/{repo_name}/blob/{branch}/\1"'
              content = re.sub(pattern3, replacement3, content)

              # Pattern 4: Markdown links with full URLs
              pattern4 = r'\[([^\]]*)\]\(https://aet-cs\.github\.io(/[^)]*\.ipynb)\)'
              replacement4 = rf'[\1](https://nbviewer.jupyter.org/github/{repo_name}/blob/{branch}\2)'
              content = re.sub(pattern4, replacement4, content)

              # Pattern 5: Markdown links with relative paths starting with /
              pattern5 = r'\[([^\]]*)\]\((/[^)]*\.ipynb)\)'
              replacement5 = rf'[\1](https://nbviewer.jupyter.org/github/{repo_name}/blob/{branch}\2)'
              content = re.sub(pattern5, replacement5, content)

              # Pattern 6: Markdown links with relative paths (no leading /)
              pattern6 = r'\[([^\]]*)\]\((?!http|/)([^)]*\.ipynb)\)'
              replacement6 = rf'[\1](https://nbviewer.jupyter.org/github/{repo_name}/blob/{branch}/\2)'
              content = re.sub(pattern6, replacement6, content)

              return content

          def fix_asset_paths(content):
              # Fix broken relative paths to assets that might have been broken by the move
              # Convert relative paths like ../../../assets to /assets
              content = re.sub(r'\.\./\.\./\.\./assets/', '/assets/', content)
              content = re.sub(r'\.\./\.\./assets/', '/assets/', content)
              content = re.sub(r'\.\./assets/', '/assets/', content)

              # Fix paths that might be looking for old white/X structure
              content = re.sub(r'/white/([^/]+)/((?!2024)[^"\s)]+)', r'/white/2024/\1/\2', content)

              return content

          # Process all markdown files
          for md_file in glob.glob("**/*.md", recursive=True):
              if "_site" in md_file or "vendor" in md_file:
                  continue

              print(f"Processing: {md_file}")
              with open(md_file, 'r', encoding='utf-8') as f:
                  content = f.read()

              original_content = content
              content = convert_notebook_links(content)
              content = fix_asset_paths(content)

              if content != original_content:
                  print(f"  Updated links in {md_file}")
                  with open(md_file, 'w', encoding='utf-8') as f:
                      f.write(content)

          # Process all HTML files
          for html_file in glob.glob("**/*.html", recursive=True):
              if "_site" in html_file or "vendor" in html_file:
                  continue

              print(f"Processing: {html_file}")
              with open(html_file, 'r', encoding='utf-8') as f:
                  content = f.read()

              original_content = content
              content = convert_notebook_links(content)
              content = fix_asset_paths(content)

              if content != original_content:
                  print(f"  Updated links in {html_file}")
                  with open(html_file, 'w', encoding='utf-8') as f:
                      f.write(content)

          print("Link conversion and path fixing complete!")
          EOF

          python convert_links.py

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
